name: VQL build and archive
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout
      with:
        ref: ${{ github.head_ref }}
    
    - name: Install Python
      uses: actions/setup-python
      with:
        python-version: '3.10'
    - name: Install python requirements
      run: |
          pip install PyYAML==6.0 -q
          pip install requests -q
          pip install pandas -q

    - name: Update vql
      run: |
          mkdir -p ./vql
          cd ./scripts
          python amcache.py
          python applications.py
          python binaryrename.py
          python evtx.py
          python iseautosave.py
          python mft.py
          python namedpipes.py
          python psreadline.py
          python webhistory.py
          python zoneidentifier.py
          python starthunts.py
          
    - name: Git Auto Commit
      uses: stefanzweifel/git-auto-commit-action
      with:
        commit_message: AutoUpdate VQL
        file_pattern: vql/*.yaml
        
    - name: Zip Folder
      run: zip -r DetectRaptorVQL.zip vql/*.yaml
    - uses: ncipollo/release-action
      with:
        artifacts: DetectRaptorVQL.zip
        tag: DetectRaptor
        allowUpdates: true
